### Shared Source Code for Analysing BCA Assays
# dataframe from victor machine 
## source code for BCA assays 

curve_fit <- function(x, 
                      y){
  require(ggplot2)
  
  ggplot(x[-1,], 
         aes(x = as.numeric(value), 
             y = mean_abs))+
    geom_point(size = 3)+
    geom_smooth(method = drm, 
                method.args = list(fct = LL.4()), 
                se = FALSE, 
                colour = "grey")+
    theme_pubr(legend = "right")+
    geom_point(data = y, aes(x = estimate, 
                             y = mean_abs,
                             colour = value), 
               shape = 18, 
               size =4)+
    labs(title = "Standard Curve and Unknown Samples", 
         x = "concentration (ug/ml)", 
         y = "absorbance (A)")+
    scale_x_log10()
}


data_import <- function(pat, # pat = date or pattern r can use to find your data file, needs to be a string unique to the file, can use whole name
                        sample.dat, # a vecotr containing standard / sample names in order as they appear on the plate A1-12, B1-12 etc  
                        replicates){ # number of replicates per sample or standard
  data.file = list.files(pattern = pat, 
                         recursive = T, 
                         path = getwd())
  data = read_excel(data.file)
  
  colnames(data)[grepl('Absorbance',colnames(data))] = "absorbance"
  
  data1 = data %>%
    mutate(value = sample.dat) 
  
  blank = subset(data1, value == 0)%>%
    pull("absorbance")  
  
  blank = blank/replicates
  
  data2 <- data1 %>%
    mutate(corrected_absorbance = absorbance - blank) 
  
  data3 <- data2 %>%
    group_by(value)%>%
    summarise_at(vars(corrected_absorbance), 
                 list(mean_abs = mean, 
                      sd = sd))
  
  data.list = list(raw_data = data1, summary_data = data3)
  
  return(data.list)
} # this function loads in your data, corrects absorbance values to the blank and generates a mean absrobance per sample/standard 

fit2curve <- function(summary.dat, # df generated from data_import() function  
                      standards, # vector containing standards i.e c(0, 25, 125, 250...) and so on 
                      samples# vector containing sample names (as they appear in summary.dat)
                      ){
  
  standard_curve = subset(summary.dat, 
                          value %in% standards) #subsetting a table to use for standard curve generation
  sample_data = subset(summary.dat,
                       value %in% samples) #subetting table of unknowns for estimation of protein conc using model created by standards
  
  model = drc::drm(mean_abs ~ as.numeric(value), 
                   fct = LL.4(), 
                   data = standard_curve) #4-parameter quadratic fit of data 
  
  concentration = ED(model,
                     sample_data$mean_abs, 
                     type = "absolute", 
                     display = F)%>%
    as.data.frame() #generating estimate protein concs of the samples based on model generated by known standards 
  
  sample_data = sample_data %>%
    mutate(estimate = concentration$Estimate, 
           std_error = concentration$`Std. Error`) #adding estimate and SD to the sample_data table 
  
  fit = curve_fit(standard_curve,
                  sample_data)
  
  list.model = list(drc.fit = model, 
                    fitted.model = fit, 
                    protein.conc = sample_data, 
                    standards = standard_curve)
  
  return(list.model) # you can now see the model, the fit and results tables stored in a list as the output of this code c()
}

