# code for processing BCA assay results 
if (!require("pacman")) install.packages("pacman") # installs the "pacman" package which allows loading and/installing of multiple packages at once
cran.packages <- c("tidyverse",
                   "rstatix",
                   "ggpubr",
                   "drc") # cran packages required for the code to work 
pacman::p_load(cran.packages, character.only = TRUE) # pacman looks for the packages in your library and installs anything if it is missing
source("https://raw.githubusercontent.com/c-triv97/Source-Codes/main/GDPR.R") # this is some general functions "General Data PRocessing" I have for things like standard error which are missing from base R 
source("https://raw.githubusercontent.com/c-triv97/Source-Codes/main/GraphThemes.r") # this is a theme for ggplot that I use 

data_import <- function(pat, skiplines = 141, path=getwd(), standard.wells = "A|B|C", nstd=3, nspl=3, nrow = 50){
  
    data.file = list.files(
        pattern = pat,
        recursive = T,
        path = path
    )
    print(data.file)

    dat = read.table( 
        file = data.file,
        sep = "\t",
        header = F,
        skip = skiplines, 
        nrows = nrow,
        fill = TRUE
    ) %>% 
    dplyr::select(
        "sample" = V1, 
        "well" = V2, 
        "known.conc" = V3,
        "absorbance.550" = V4
    ) %>% 
    mutate(
        absorbance.550 = as.numeric(
            str_replace(
                absorbance.550,
                ",", 
                "."
            )
        )
    )

    blank = filter(dat, known.conc == 0) %>% 
    pull("absorbance.550")%>% 
    mean()

    dat = dat %>% 
    mutate(corr.absorbance.550 = absorbance.550 - blank)

    nstandards = length(grep("STD", dat$sample, value = FALSE))

    standards = dat %>% 
    filter(
        grepl(
            standard.wells, 
            well
        )
    ) %>% 
    drop_na(known.conc) %>% # removing blanks 
    arrange(as.numeric(known.conc)) %>% #this is incase the ordering in the original sheet is not sequential
    mutate(
        sample = rep(c(LETTERS[nstandards:1]),times=c(rep(nstd,nstandards)))
    ) %>% 
    group_by(
        sample, known.conc
    ) %>% 
    summarise( 
        mean.absorbance = mean(corr.absorbance.550), 
        sd.absorbance = sd(corr.absorbance.550), 
        replicates = n()
    )

    nsamples = length(grep("SPL", dat$sample, value = FALSE))

    unknowns = dat %>% 
    filter(
        !grepl(
            standard.wells, 
            well
        ),
        !corr.absorbance.550 < 0
    ) %>% 
    mutate(
        sample = rep(c(1:nsamples),times=c(rep(nspl,nsamples)))
    ) %>% 
    group_by(
        sample
    ) %>% 
    summarise( 
        mean.absorbance = mean(corr.absorbance.550), 
        sd.absorbance = sd(corr.absorbance.550), 
        replicates = n()
    )

    data.list = list(raw_data = dat, standards = standards, unknowns = unknowns)
  
  return(data.list)
}

fit2curve <- function(standards, unknowns, plt = TRUE){

    model <- drc::drm(
    mean.absorbance ~ known.conc, 
    fct = LL.4(), 
    data = standards) #4-parameter quadratic fit of data 

    concentration <- ED(
        model,
        unknowns$mean.absorbance, 
        type = "absolute", 
        display = F)%>%
    as.data.frame() #generating estimate protein concs of the samples based on model generated by known standards

    # adding data back to the unknowns table
    unknowns <- unknowns %>% 
        mutate(estimate = concentration$Estimate, 
            std_error = concentration$`Std. Error`)
    
    if(plt==TRUE){
        p = ggplot(filter(standards, known.conc !=0),
            aes(x = known.conc, 
                y = mean.absorbance))+
        geom_point(size = 3)+
        geom_smooth(method = drm, 
                    method.args = list(fct = LL.4()), 
                    se = FALSE, 
                    colour = "grey")+
        theme_scientific +
        geom_point(data = unknowns, 
                   aes(x = estimate, 
                   y = mean.absorbance,
                   fill = as.factor(sample)),
                   colour="black",pch=21, 
                   size =4)+
        labs(title = "Standard Curve and Unknown Samples", 
             x = "concentration (ug/ml)", 
             y = "absorbance (A)")+
        scale_fill_discrete(name = "Sample ID")+
        scale_x_continuous(breaks = rev(standards$known.conc[-9]),
                           transform = "pseudo_log")+
        guides(x = "axis_logticks")

        print(p)
        
        return(list(
                plt=p,
                drc.fit = model,  
                protein.conc = unknowns, 
                standards = standards
            )
        )
    }else{

        return(list(
                drc.fit = model,  
                protein.conc = unknowns, 
                standards = standards
            ))
   }
}

western_vols <- function(data, 
                         ug, 
                         vol,
                         sb=5){
  sb.ul = vol/sb 
  
  out = data %>%
    mutate(vol.req.ul = (ug / (`estimate` / 1) * 1000))%>%
    mutate(diluent.ul = vol - vol.req.ul - sb.ul, 
           sb.ul = sb.ul)

  return(out)
}
